name: Ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_format:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - default
          - profile-with-puffin
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/ruff-action@v3
    - run: ruff format --check --diff" 
